name: Deployment to QA Environment HP-1
on:
  pull_request:
    branches: [main]
    types:
      - closed
jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest #Os
    environment: qa   #For Environment
    steps:
      - uses: actions/checkout@master
      - name: Example of consumption of the output
        run: |
          echo "hello world"
