on:
  push:
    branches: [feature/*]
name: Get Github Release Data
jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest #Os
    environment: test   #For Environment
    steps:
      - uses: actions/checkout@master
      - name: Example of consumption of the output
        run: |
          echo "hello world"
